call ..\venv\Scripts\activate
echo Running sim0_proposed_m64.py...
python sim0_proposed_m64.py
echo Running sim0_proposed_pe.py...
python sim0_proposed_pe.py
echo Running sim1_massive_spread.py...
python sim1_massive_spread.py
echo Running sim2_ablation.py...
python sim2_ablation.py
echo Running sim3_severe_shift.py...
python sim3_severe_shift.py
echo All ablation/edge-case tests finished.
